// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Infrastructure.Persistence;

#nullable disable

namespace MyShop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MyShopDbContext))]
    [Migration("20260923215856_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.AttributeDefinitionPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId", "Code")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.CategoryPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.PriceRulePersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId", "Priority");

                    b.ToTable("PriceRules", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductAttributeMultiChoiceValuePersistence", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "AttributeDefinitionId", "Ordinal");

                    b.ToTable("ProductAttributeMultiChoiceValues", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductAttributeValuePersistence", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<string>("ChoiceValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<decimal?>("DecimalCoefficient")
                        .HasPrecision(29)
                        .HasColumnType("decimal(29,0)");

                    b.Property<byte?>("DecimalScale")
                        .HasColumnType("tinyint");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "AttributeDefinitionId");

                    b.ToTable("ProductAttributeValues", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductCategoryPersistence", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductTypePersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeMultiChoiceValuePersistence", b =>
                {
                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductVariantId", "AttributeDefinitionId", "Ordinal");

                    b.ToTable("ProductVariantAttributeMultiChoiceValues", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeValuePersistence", b =>
                {
                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<string>("ChoiceValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<decimal?>("DecimalCoefficient")
                        .HasPrecision(29)
                        .HasColumnType("decimal(29,0)");

                    b.Property<byte?>("DecimalScale")
                        .HasColumnType("tinyint");

                    b.Property<long?>("IntegerValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductVariantId", "AttributeDefinitionId");

                    b.ToTable("ProductVariantAttributeValues", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductVariants_Sku")
                        .HasFilter("[Sku] IS NOT NULL");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.AttributeDefinitionPersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductTypePersistence", "ProductType")
                        .WithMany("AttributeDefinitions")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.CategoryPersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.CategoryPersistence", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.PriceRulePersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductVariantPersistence", "ProductVariant")
                        .WithMany("PriceRules")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductAttributeMultiChoiceValuePersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductAttributeValuePersistence", "AttributeValue")
                        .WithMany("MultiChoiceValues")
                        .HasForeignKey("ProductId", "AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductAttributeValuePersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductPersistence", "Product")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductCategoryPersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductPersistence", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductPersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductTypePersistence", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeMultiChoiceValuePersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeValuePersistence", "AttributeValue")
                        .WithMany("MultiChoiceValues")
                        .HasForeignKey("ProductVariantId", "AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeValuePersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductVariantPersistence", "ProductVariant")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantPersistence", b =>
                {
                    b.HasOne("MyShop.Infrastructure.Persistence.Models.ProductPersistence", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.CategoryPersistence", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductAttributeValuePersistence", b =>
                {
                    b.Navigation("MultiChoiceValues");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductPersistence", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Categories");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductTypePersistence", b =>
                {
                    b.Navigation("AttributeDefinitions");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantAttributeValuePersistence", b =>
                {
                    b.Navigation("MultiChoiceValues");
                });

            modelBuilder.Entity("MyShop.Infrastructure.Persistence.Models.ProductVariantPersistence", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("PriceRules");
                });
#pragma warning restore 612, 618
        }
    }
}
