using MyShop.Application.Catalog.GetProductAttributeValidation;
using Microsoft.Extensions.DependencyInjection;
using MyShop.Application.Catalog.AddProductVariant;
using MyShop.Application.Catalog.AddProductVariantPriceRule;
using MyShop.Application.Catalog.AddProductTypeAttribute;
using MyShop.Application.Catalog.AssignProductToCategory;
using MyShop.Application.Catalog.ClearProductVariantSku;
using MyShop.Application.Catalog.ClearProductVariantPrice;
using MyShop.Application.Catalog.CreateProduct;
using MyShop.Application.Catalog.CreateCategory;
using MyShop.Application.Catalog.CreateProductType;
using MyShop.Application.Catalog.DeleteCategory;
using MyShop.Application.Catalog.DeleteProductType;
using MyShop.Application.Catalog.DeleteProduct;
using MyShop.Application.Catalog.ConfigureProductTypeAttribute;
using MyShop.Application.Catalog.GetCategory;
using MyShop.Application.Catalog.GetProduct;
using MyShop.Application.Catalog.GetProductBySku;
using MyShop.Application.Catalog.GetProductType;
using MyShop.Application.Catalog.ListCategories;
using MyShop.Application.Catalog.ListProducts;
using MyShop.Application.Catalog.ListProductTypes;
using MyShop.Application.Catalog.MoveCategory;
using MyShop.Application.Catalog.RemoveProductAttributeValue;
using MyShop.Application.Catalog.RemoveProductTypeAttribute;
using MyShop.Application.Catalog.RemoveProductFromCategory;
using MyShop.Application.Catalog.RemoveProductVariant;
using MyShop.Application.Catalog.RemoveProductVariantPriceRule;
using MyShop.Application.Catalog.RemoveVariantAttributeValue;
using MyShop.Application.Catalog.RenameProduct;
using MyShop.Application.Catalog.RenameCategory;
using MyShop.Application.Catalog.RenameProductType;
using MyShop.Application.Catalog.RenameProductTypeAttribute;
using MyShop.Application.Catalog.RenameProductVariant;
using MyShop.Application.Catalog.SetProductAttributeValue;
using MyShop.Application.Catalog.SetProductVariantSku;
using MyShop.Application.Catalog.SetProductVariantPrice;
using MyShop.Application.Catalog.SetProductVariantStock;
using MyShop.Application.Catalog.ClearProductVariantStock;
using MyShop.Application.Catalog.SetVariantAttributeValue;
using MyShop.Application.Catalog.GetProductTypeUsage;
using MyShop.Application.Catalog.GetCategoryUsage;
using MyShop.Application.Catalog.GetProductTypeAttribute;
using MyShop.Application.Catalog.GetVariantAttributeValue;
using MyShop.Application.Catalog.GetProductAttributeValue;
using MyShop.Application.Catalog.GetProductVariant;
using MyShop.Application.Catalog.ListProductVariantPriceRules;
using MyShop.Application.Catalog.GetProductVariantPriceRule;
using MyShop.Application.Catalog.GetProductVariantPrice;
using MyShop.Application.Catalog.UpdateProductVariantPriceRule;

namespace MyShop.Application;

public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddMyShopApplication(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddScoped<AddProductVariant>();
        services.AddScoped<AddProductVariantPriceRule>();
        services.AddScoped<AddProductTypeAttribute>();
        services.AddScoped<AssignProductToCategory>();
        services.AddScoped<ClearProductVariantSku>();
        services.AddScoped<ClearProductVariantPrice>();
        services.AddScoped<CreateProduct>();
        services.AddScoped<CreateCategory>();
        services.AddScoped<CreateProductType>();
        services.AddScoped<DeleteCategory>();
        services.AddScoped<DeleteProductType>();
        services.AddScoped<DeleteProduct>();
        services.AddScoped<ConfigureProductTypeAttribute>();
        services.AddScoped<GetCategory>();
        services.AddScoped<GetProduct>();
        services.AddScoped<GetProductBySku>();
        services.AddScoped<GetProductType>();
        services.AddScoped<ListCategories>();
        services.AddScoped<ListProducts>();
        services.AddScoped<ListProductTypes>();
        services.AddScoped<MoveCategory>();
        services.AddScoped<RemoveProductAttributeValue>();
        services.AddScoped<RemoveProductTypeAttribute>();
        services.AddScoped<RemoveProductFromCategory>();
        services.AddScoped<RemoveProductVariant>();
        services.AddScoped<RemoveProductVariantPriceRule>();
        services.AddScoped<RemoveVariantAttributeValue>();
        services.AddScoped<RenameProduct>();
        services.AddScoped<RenameCategory>();
        services.AddScoped<RenameProductType>();
        services.AddScoped<RenameProductTypeAttribute>();
        services.AddScoped<RenameProductVariant>();
        services.AddScoped<SetProductAttributeValue>();
        services.AddScoped<SetProductVariantSku>();
        services.AddScoped<SetProductVariantPrice>();
        services.AddScoped<SetProductVariantStock>();
        services.AddScoped<ClearProductVariantStock>();
        services.AddScoped<SetVariantAttributeValue>();

        services.AddScoped<UpdateProductVariantPriceRule>();
        services.AddScoped<GetProductVariantPrice>();
        services.AddScoped<GetProductVariantPriceRule>();
        services.AddScoped<ListProductVariantPriceRules>();
        services.AddScoped<GetProductVariant>();
        services.AddScoped<GetProductAttributeValue>();
        services.AddScoped<GetVariantAttributeValue>();

        services.AddScoped<GetProductTypeAttribute>();
        services.AddScoped<GetCategoryUsage>();
        services.AddScoped<GetProductTypeUsage>();

        services.AddScoped<GetProductAttributeValidation>();

        services.AddScoped<Catalog.UpdateProductPresentation.UpdateProductPresentation>();
        services.AddScoped<Catalog.BrowseStorefront.BrowseStorefront>();
        services.AddScoped<Catalog.ListStorefrontCategories.ListStorefrontCategories>();
        services.AddScoped<Catalog.GetStorefrontProduct.GetStorefrontProduct>();
        services.AddScoped<Catalog.GetStorefrontPrices.GetStorefrontPrices>();
        services.AddScoped<Catalog.QuoteStorefrontCart.QuoteStorefrontCart>();
        services.AddScoped<Checkout.GetPaymentOptions.GetPaymentOptions>();
        services.AddScoped<Checkout.GetAdminPaymentOptions.GetAdminPaymentOptions>();
        services.AddScoped<Checkout.UpdatePaymentOptions.UpdatePaymentOptions>();
        services.AddScoped<Checkout.ManageDeliveryMethods.ListDeliveryMethods>();
        services.AddScoped<Checkout.ManageDeliveryMethods.SaveDeliveryMethod>();
        services.AddScoped<Checkout.ManageDeliveryMethods.DeleteDeliveryMethod>();
        services.AddScoped<Checkout.PlaceOrder.PlaceOrder>();
        services.AddScoped<Checkout.StartOnlinePayment.StartOnlinePayment>();
        services.AddScoped<Checkout.ListOrders.ListOrders>();
        services.AddScoped<Checkout.GetOrder.GetOrder>();
        services.AddScoped<Checkout.MarkOrderPaid.MarkOrderPaid>();
        services.AddScoped<Checkout.MarkOrderShipped.MarkOrderShipped>();
        services.AddScoped<Checkout.CancelOrder.CancelOrder>();
        services.AddScoped<Checkout.RefundOrder.RefundOrder>();
        services.AddScoped<Customers.GetCustomerProfile.GetCustomerProfile>();
        services.AddScoped<Customers.UpdateCustomerProfile.UpdateCustomerProfile>();
        services.AddScoped<Customers.ListCustomerOrders.ListCustomerOrders>();
        services.AddScoped<Customers.GetCustomerOrder.GetCustomerOrder>();
        services.AddScoped<Customers.CancelCustomerOrder.CancelCustomerOrder>();
        services.AddScoped<Customers.ManageCustomers.ListManagedCustomers>();
        services.AddScoped<Customers.ManageCustomers.GetManagedCustomer>();
        services.AddScoped<Customers.ManageCustomers.SetCustomerLock>();
        services.AddScoped<Customers.ManageWishlist.ListWishlist>();
        services.AddScoped<Customers.ManageWishlist.GetWishlistState>();
        services.AddScoped<Customers.ManageWishlist.AddWishlistItem>();
        services.AddScoped<Customers.ManageWishlist.RemoveWishlistItem>();
        services.AddScoped<Dashboard.GetDashboard.GetDashboard>();
        return services;
    }
}
